cart/urls.py
from django.urls import path
from cart import views
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-to-cart', views.addtocart, name='addtocart'),
    path('add-cart-qty', views.addcartquantity, name='addcartquantity'),
    path('remove-from-cart', views.removefromcart, name='removefromcart'),
]

caviar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('brands/', include('brands.urls')),
    path('category', include('category.urls')),
    path('order/', include('order.urls')),


    path('signin/', include('security.urls')),
    path('userdetails/', include('userdetails.urls')),

    path('caviar-admin/', include('caviaradmin.urls')),

    path('coupons/', include('coupons.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views
urlpatterns = [
    path('', views.order, name='order'),
    path('checkout/', views.checkout, name="checkout"),
    path('confirm/', views.confirm, name="confirm"),
    path('success/', views.success, name='success'),


    path('order-details/<int:id>/',
         views.userordersdetails, name='userordersdetails'),
    path('cancelorder', views.cancelorder, name='cancelorder'),

    path('return-product/', views.returnproduct, name='returnproduct'),



    path('proceed-to-pay/', views.proceed_to_pay, name='proceedtopay'),


    path('orders/', views.orders, name='orders'),
    path('orders-details/<int:id>/', views.ordersdetails, name='ordersdetails'),
    path('orderstatus/', views.orderstatus, name='orderstatus'),



]

order/models.py
from django.db import models
from product.models import ProductVarient, Products

from security.models import CustomUser
from userdetails.models import Address


class Order(models.Model):

    user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, blank=True, null=True
    )
    address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    payment_id = models.CharField(max_length=200)
    payment_method = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    wallet_amount = models.FloatField(default=0, blank=True, null=True)
    deliverycharge = models.FloatField(default=0, blank=True, null=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.user.username + " " + self.order_number


class OrderItems(models.Model):
    STATUS = (
        ("Order Processing", "Order Processing"),
        ("Confirmed", "Confirmed"),
        ("Shipped", "Shipped"),
        ("Delivered", "Delivered"),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVarient, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True)
    unitprice = models.FloatField(blank=True, null=True)
    product_price = models.FloatField(blank=True)
    profit = models.FloatField(blank=True, null=True)
    reason = models.TextField(max_length=2000, blank=True)
    is_cancelled = models.BooleanField(default=False)
    returndate = models.DateTimeField(null=True, blank=True)
    status = models.CharField(
        max_length=20, choices=STATUS, default="Order Processing")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.product.product.name


class Review(models.Model):
    user = models.CharField(max_length=255, blank=True, null=True)
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE, null=True, blank=True)
    review = models.TextField(max_length=3000, blank=True)
    orderitems = models.ForeignKey(
        OrderItems, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user+" "+self.product.name

order/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from cart.models import Cart
from order.models import Order, OrderItems, Review
import datetime
from datetime import timedelta
from django.utils import timezone
import random
from product.models import ProductVarient
from security.models import CustomUser
from userdetails.models import Address
from django.views.decorators.cache import cache_control

# Create your views here.


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def order(request):
    temp = request.user
    user = CustomUser.objects.get(username=temp)
    items = Order.objects.filter(user=user)
    context = {
        'items': items
    }

    return render(request, 'order/order.html', context)


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def checkout(request):
    temp = request.user
    user = CustomUser.objects.get(username=temp)
    cart = Cart.objects.filter(user=user)
    if cart:

        userwallet = user.wallet
        address = Address.objects.filter(user=user)

        if request.method == "POST":
            deliveryaddressid = request.POST.get('address')
            paymentmethod = request.POST.get('paymentmethod')
            wallet = request.POST.get('wallet')
            context = {
                "address": deliveryaddressid,
                'paymentmethod': paymentmethod,
                'wallet': wallet
            }
            request.session['order'] = context

            return redirect('confirm')
        context = {
            "address": address,
            'userwallet': userwallet
        }
        return render(request, 'order/checkout.html', context)
    else:
        return redirect('offers')


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def confirm(request):
    if 'order' in request.session:
        address = request.session.get('order')
        paymentmethod = address['paymentmethod']
        addressid = address['address']
        usewallet = address['wallet']

        temp = request.user
        user = CustomUser.objects.get(username=temp)
        items = Cart.objects.filter(user=user)

        grandtotal = 0
        for i in items:
            if i.product.quantity > 0:
                grandtotal += i.totalprice()

        delivercharge = 0
        if grandtotal < 1000:
            delivercharge += 70
            grandtotal += 70

        wallet = 0
        if usewallet:
            if user.wallet > grandtotal:
                wallet = grandtotal
            elif user.wallet < grandtotal:
                wallet = user.wallet
        balance = float(grandtotal)-float(wallet)

        current_datetime = datetime.datetime.now()
        datetimenow = f"{current_datetime:%Y%m%d%H%M%S}"
        randomnumber = str(random.randint(11111, 99999))
        ordernumber = datetimenow+randomnumber

# for saving order
        if request.method == "POST":

            if usewallet:

                if user.wallet > grandtotal:
                    user.wallet = float(user.wallet) - float(grandtotal)
                    user.save()

                elif user.wallet < grandtotal:
                    user.wallet = 0
                    user.save()

            address = Address.objects.get(id=addressid)
            order = Order()
            order.user = user
            order.address = address
            order.order_number = ordernumber
            order.order_total = grandtotal
            order.wallet_amount = wallet
            order.deliverycharge = delivercharge
            order.save()

            if paymentmethod == 'cod':
                if balance == 0:
                    order.payment_method = 'WALLET'
                    order.payment_id = ordernumber+str(user.id)+'WALLET'
                else:
                    order.payment_method = 'COD'
                    order.payment_id = ordernumber+str(user.id)+'COD'

                order.save()
            else:
                if balance == 0:
                    order.payment_method = 'WALLET'
                    order.payment_id = ordernumber+str(user.id)+'WALLET'

                else:
                    paymentid = request.POST.get('payment_id')
                    order.payment_id = paymentid+str(user.id)+'UPI'
                    order.payment_method = 'UPI'

                order.save()
            # for order items
            for i in items:
                orderitems = OrderItems()
                productvarient = ProductVarient.objects.get(id=i.product.id)
                if productvarient.quantity > 0:
                    orderitems.order = order
                    orderitems.product = productvarient
                    orderitems.quantity = i.quantity
                    orderitems.unitprice = productvarient.product.discountprice
                    orderitems.product_price = productvarient.product.discountprice*i.quantity
                    orderitems.profit = (float(productvarient.product.discountprice)-float(
                        productvarient.product.costoftheproduct))*i.quantity
                    orderitems.save()
                    productvarient.quantity -= i.quantity
                    productvarient.save()
                    i.delete()
            return redirect('success')
        context = {
            'items': items,
            "grandtotal": grandtotal,
            'paymentmethod': paymentmethod,
            'wallet': wallet,
            'delivercharge': delivercharge,
            'balance': balance
        }

        return render(request, 'order/confirm.html', context)
    else:
        return redirect('offers')


# for razorpay
@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def proceed_to_pay(request):
    address = request.session.get('order')
    usewallet = address['wallet']
    temp = request.user
    user = CustomUser.objects.get(username=temp)
    items = Cart.objects.filter(user=user)
    grandtotal = 0
    for i in items:
        if i.product.quantity > 0:
            grandtotal += i.totalprice()
    if grandtotal < 1000:
        grandtotal += 70

    if usewallet:
        grandtotal = float(grandtotal) - float(user.wallet)

    payable_amount = grandtotal
    return JsonResponse({
        'payable_amount': payable_amount,
    })


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def success(request):
    if 'order' in request.session:
        del request.session['placeorder']
        del request.session['order']
        return render(request, 'order/success.html')
    else:
        return redirect('offers')


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def userordersdetails(request, id):
    order = Order.objects.get(id=id)
    items = OrderItems.objects.filter(order=order)
    today = timezone.now()
    balancetopay = float(order.order_total) - float(order.wallet_amount)
    if order.payment_method == 'UPI':
        balancetopay = 0.00
    context = {
        'items': items,
        'order': order,
        'balancetopay': balancetopay,
        'today': today,
    }

    return render(request, 'order/userorder.html', context)


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def cancelorder(request):
    if request.method == 'POST':
        reason = request.POST.get('reason')
        itemId = request.POST.get('itemId')

        item = OrderItems.objects.get(id=itemId)
        item.is_cancelled = True
        item.reason = reason
        item.save()

        product = ProductVarient.objects.get(id=item.product.id)
        product.quantity += item.quantity
        product.save()

        order = Order.objects.get(id=item.order.id)
        order.order_total = float(order.order_total) - \
            float(item.product_price)
        order.save()

        user = order.user

        walletused = order.wallet_amount
        odertotal = order.order_total

        if walletused > odertotal:
            user.wallet = float(user.wallet) + \
                (float(walletused)-float(odertotal))
            order.wallet_amount = float(
                walletused)-(float(walletused)-float(odertotal))
            user.save()
            order.save()
        elif order.payment_method == 'UPI':
            user.wallet = float(user.wallet) + float(item.product_price)
            user.save()

        orderitem = OrderItems.objects.filter(order=order, is_cancelled=False)
        itemcount = orderitem.count()

        delivrycharge = 0
        if order.deliverycharge > 0:
            delivrycharge = 70

        if itemcount == 0:
            user.wallet = float(user.wallet) + float(delivrycharge)
            user.save()
            order.deliverycharge = 0
            order.order_total = 0
            order.save()

        return JsonResponse({"is_valid": True})


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='signin')
def returnproduct(request):
    name = request.user.username
    user = CustomUser.objects.get(username=name)
    if request.method == 'POST':
        reason = request.POST.get('reason')
        itemId = request.POST.get('itemId')

        item = OrderItems.objects.get(id=itemId)
        item.is_cancelled = True
        item.reason = reason
        item.save()

        product = ProductVarient.objects.get(id=item.product.id)
        product.quantity += item.quantity
        product.save()

        order = Order.objects.get(id=item.order.id)
        order.order_total = float(order.order_total) - \
            float(item.product_price)
        order.save()

        user = order.user
        user.wallet = float(user.wallet) + float(item.product_price)
        user.save()

        delivrycharge = 0
        if order.deliverycharge > 0:
            delivrycharge = 70

templates/order/aorder.html
{%extends 'admin/dashboard.html'%} {%block title%} Orders {%endblock%} 
{% block bodycontent%}

<div class="text-center">
    
    {%for i in items%}
    <div class="effect d-inline-block mx-2 mb-3 text-center py-2 px-4 rounded-5 ">
    
    <p class="mb-2">orderby {{i.user.username}}
       at {{i.created}},
         {%if i.order_total == 0 %} <span class="text-danger">order cancelled</span>{%else%}total  {{i.order_total}}{%endif%}</p>
    <a class="button mb-1" href="{%url 'ordersdetails' i.id%}">view order details</a>
    </div>
    {%endfor%}
    </div>


{%endblock%} 

templates/order/confirm.html
{%extends 'shop/shop.html'%} {%block title%} Order Confirmation {%endblock%} 
{% block bodycontent%}

<div class="d-flex justify-content-center text-uppercase">
  <div class="effect d-inline-block mx-2 mb-3 py-2 px-4 rounded-2">
    <p class="mb-1"><strong>selected items</strong></p>

    {%for i in items%} {%if i.product.quantity > 0%}

    <p class="text_md mb-1">
      <em
        >{{forloop.counter}}. {{i.product.product.name}} <br />
        Qty: {{i.quantity}} total: ₹{{i.total}}
      </em>
    </p>
    {%endif%}{%endfor%} {%if delivercharge > 0 %}
    <p>
      delivery charge: <strong class="text-danger">{{delivercharge}}</strong>
    </p>
    {%else%}
    <p>delivery charge: <strong class="text-danger">free delivery</strong></p>
    {%endif%}
    <p>paymentmethod: <strong class="text-danger">{{paymentmethod}}</strong></p>

    <p class="grandtotal">
      Total of : <strong class="text-danger">{{grandtotal  }}</strong>
    </p>
    {% if wallet > 0 %}
    <p>wallet used: <strong class="text-danger">{{wallet}}</strong></p>
    {%endif%}
    <p>balance to pay:<strong class="text-danger"> {{balance}}</strong></p>

    <br />
    <form action="" method="post">
      {%csrf_token%} {%if paymentmethod == 'upi' and balance != 0%}

      <button class="button payWithRazorpay" type="button" id="rzp-button1">
        pay now
      </button>

      {%elif paymentmethod == 'cod' or balance == 0 %}

      <input class="button" type="submit" value="Confirm order" />

      {%endif%}
    </form>
  </div>
</div>

{%endblock%} {%block script%}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>

<script>
  $(".payWithRazorpay").click(function (e) {
    e.preventDefault();
    var paymentMethod = "upi";
    var token = $("[name='csrfmiddlewaretoken']").val();
    // fetch values
    console.log(paymentMethod);

    $.ajax({
      url: "{% url 'proceedtopay' %}",
      method: "GET",
      success: function (response) {
        console.log(response);
        var options = {
          key: "rzp_test_1eGRi3b8lZzHRv", // Enter the Key ID generated from the Dashboard
          amount: response.payable_amount * 100, // `Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
          currency: "INR",
          currency: "INR",
          name: "Caviar",
          description: "total amount to pay",
          image: "https://caviar.global/tpl/img/logo.en.png",
          // "order_id": "order_IluGWxBm9U8zJ8", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
          handler: function (response_a) {
            // alert(response_a.razorpay_payment_id);
            data = {
              paymentMethod: paymentMethod,
              payment_id: response_a.razorpay_payment_id,
              csrfmiddlewaretoken: token,
            };

            $.ajax({
              type: "POST",
              url: "{% url 'confirm' %}",
              data: data,
              success: (res) => {
                alert("order successfull");
                location.href = "/order/success/";
              },
            });
          },
          prefill: {
            name: "Gaurav Kumar",
            email: "gaurav.kumar@example.com",
            contact: "9000090000",
          },
          notes: {
            address: "Razorpay Corporate Office",
          },
          theme: {
            color: "#3399cc",
          },
        };
        var rzp1 = new Razorpay(options);

        rzp1.open();
      },
    });
  });
</script>
{%endblock%}

templates/order/order.html
{%extends 'shop/shop.html'%} {%block title%} Orders {%endblock%} {% block bodycontent%}


<div class="text-center">
    {%if items%}
  {%for i in items%}
  <div class="effect d-inline-block mx-2 mb-3 text-center py-2 px-4 rounded-5">
    <p class="mb-2">
      order for {{i.address.name}}, at {{i.created}}, {%if i.order_total == 0 %} <span class="text-danger">order cancelled</span>{%else%}total
      {{i.order_total}}{%endif%}
    </p>
    <a class="button mb-1" href="{%url 'userordersdetails' i.id%}"
      >view order details</a
    >
  </div>
  {%endfor%}
  {%else%}
  <h3 class="text-danger text-uppercase">no orders yet</h3>
  {%endif%}
</div>

{%endblock%}

templates/order/userorder.html
{%extends 'shop/shop.html'%} {%block title%} Order Details {%endblock%} 
{% block bodycontent%}

<!-- for cancel -->

<div
  class="modal fade"
  id="cancelConfimation"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="cancelConfimationLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="cancelConfimationLabel">
          Confimation
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="" id="cancelConfimationForm" method="post">
          {%csrf_token%}
          <div class="mb-3 border_bottom">
            <label for="reason">Reson for Cancellation</label>
            <input
              class="form-control"
              required
              type="text"
              name="reason"
              id="reason"
            />
          </div>

          <div class="">
            <p class="button" data-bs-dismiss="modal">cancel</p>
            <input class="button bg-danger" type="submit" value="Confirm" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- for return -->

<div
  class="modal fade"
  id="returnConfirmation"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="returnConfirmationLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="returnConfirmationLabel">
          Confimation
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="" id="returnConfirmationForm" method="post">
          {%csrf_token%}
          <div class="mb-3 border_bottom">
            <label for="reason">Reason for return</label>
            <input
              class="form-control"
              required
              type="text"
              name="reason"
              id="reason"
            />
          </div>

          <div class="">
            <p class="button" data-bs-dismiss="modal">cancel</p>
            <input class="button bg-danger" type="submit" value="Return" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- for review -->
<div
  class="modal fade"
  id="review"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="reviewLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="reviewLabel">Review</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="" id="reviewForm" method="post">
          {%csrf_token%}
          <div class="mb-3 border_bottom">
            <input
              class="form-control"
              required
              type="text"
              name="review"
              id="review"
            />
          </div>

          <div class="">
            <p class="button" data-bs-dismiss="modal">cancel</p>
            <input class="button bg-danger" type="submit" value="Send" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div
  class="row mx-1 mb-3 row-gap-2 justify-content-center mx-2 row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xxl-4 row-gap-3 p-0"
>
  {%for i in items%}
  <div class="col overflow-hidden p-0">
    <div class="m-1 p-1 rounded-2 effect d-flex">
      <div class="row row-gap-3 row-cols-2">
        <div class="col">
          <img
            class="img-fluid rounded-5"
            src="{{i.product.product.image.url}}"
            alt=""
            loading="lazy"
          />
        </div>

        <div class="col d-flex align-items-center text_md">
          <div class="w-100">
            <p class="text-danger">status: {{i.status}}</p>

            <div class="mb-2">
              <a href="{%url 'product' i.product.product.id%}"
                ><p class="text-break link_text">
                  {{i.product.product.name}}
                </p></a
              >
              <p>Qty: {{ i.quantity }}</p>
              <p>Size: {{i.product.size}}</p>
              <p>Unit Price: {{ i.unitprice}}</p>
              <p>Total Price: {{ i.product_price}}</p>
            </div>
          </div>
        </div>
        <div class="col-12 text-center">
          {%if i.is_cancelled%}
          <p class="text-danger p-1">Order Cancelled:{{i.reason}}</p>
          {%elif i.status == 'Delivered' %} {%if i.returndate > today %}
          <button
            type="button"
            class="button mb-2 return-item-button"
            data-item-id="{{i.id}}"
            data-bs-toggle="modal"
            data-bs-target="#returnConfirmation"
          >
            return
          </button>

          {%endif%} {%else%}
          <button
            type="button"
            class="button mb-2 cancel-item-button"
            data-item-id="{{i.id}}"
            data-bs-toggle="modal"
            data-bs-target="#cancelConfimation"
          >
            cancel item
          </button>
          {%endif%}
      <div class="text-start p-1">
        
        {% if i.status == 'Delivered' %}
        <h5>Review:</h5>
        
        {% if i.review_set.all%}
        {{i.review_set.first.review}}
        <button
          type="button"
          class="mb-2 write-review"
          data-item-id="{{i.id}}"
          data-bs-toggle="modal"
          data-bs-target="#review"
        >
        <svg
                xmlns="http://www.w3.org/2000/svg"
                class="product_svg"
                fill="currentColor"
                viewBox="0 0 16 16"
              >
                <path
                  d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
                />
                <path
                  fill-rule="evenodd"
                  d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
                />
              </svg>
        </button>
        
        {%else%}
        <button
          type="button"
          class="button mb-2 write-review"
          data-item-id="{{i.id}}"
          data-bs-toggle="modal"
          data-bs-target="#review"
        >
          write a review
        </button>
        {%endif%} {%endif%}
      </div>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>

{% if order.order_total > 0 %}
<div class="text-center">
  <div class="effect d-inline-block mx-2 mb-3 py-2 px-4 rounded-5">
    <p>delivey address</p>
    <p>{{order.address.name}} {{order.address.type_of_address}}</p>
    <p>
      {{order.address.phone_number}}, {{order.address.alternate_phone_number}}
      <br />{{order.address.house}}<br />{{order.address.road}}<br />
      {{order.address.pincode}} {{order.address.city}} {{order.address.state}}
    </p>
  </div>
  <div
    class="effect text-start align-top d-inline-block mx-2 mb-3 py-2 px-4 rounded-5"
  >
    <p>
      payment method:<strong class="text-danger"
        >{{order.payment_method}}</strong
      >
    </p>
    {% if balancetopay == 0 %}
    <p>payment id: <strong class="text-danger">{{order.payment_id}}</strong></p>
    {%endif%}
    <p>
      amount paid using wallet:
      <strong class="text-danger">{{order.wallet_amount}} </strong>
    </p>

    {%if order.deliverycharge > 0 %}
    <p>
      delivery charge:
      <strong class="text-danger">{{order.deliverycharge}}</strong>
    </p>
    {%else%}
    <p>delivery charge: <strong class="text-danger">free delivery</strong></p>
    {%endif%}
    <p>
      balance amount to pay:
      <strong class="text-danger">{{ balancetopay }}</strong>
    </p>

    {%if order.payment.amountpaid%}

    <p>transaction id : {{order.payment.paymentid}}</p>
    {%endif%}
  </div>
</div>
{%endif%} {%endblock%} {%block script%}
<script>
  $(document).ready(function () {
    var itemId;

    // Handle "Cancel Item" button click
    $(".cancel-item-button").click(function () {
      itemId = $(this).data("item-id");
    });

    // Handle form submission
    $("#cancelConfimationForm").on("submit", function (event) {
      event.preventDefault();

      var formData = new FormData(this);

      var formData = new FormData(this);
      formData.append("itemId", itemId);

      $.ajax({
        type: "POST",
        url: '{% url "cancelorder" %}',
        data: formData,
        processData: false,
        contentType: false,
        success: function (data) {
          if (data.is_valid) {
            location.reload();
          } else {
            alert("hu");
          }
        },
        error: function () {
          alert("hkjhkju");
        },
      });
    });
  });

  // return
  $(document).ready(function () {
    var itemId;

    // Handle "Cancel Item" button click
    $(".return-item-button").click(function () {
      itemId = $(this).data("item-id");
    });

    // Handle form submission
    $("#returnConfirmationForm").on("submit", function (event) {
      event.preventDefault();

      var formData = new FormData(this);

      var formData = new FormData(this);
      formData.append("itemId", itemId);

      $.ajax({
        type: "POST",
        url: '{% url "returnproduct" %}',
        data: formData,
        processData: false,
        contentType: false,
        success: function (data) {
          if (data.is_valid) {
            setTimeout(function () {
              location.reload();
            }, 1000);
          } else {
            alert("oops....");
          }
        },
        error: function () {
          alert("Task not Done");
        },
      });
    });
  });

  // for review
  $(document).ready(function () {
    var itemId;

    // Handle "Cancel Item" button click
    $(".write-review").click(function () {
      itemId = $(this).data("item-id");
    });

    // Handle form submission
    $("#reviewForm").on("submit", function (event) {
      event.preventDefault();

      var formData = new FormData(this);

      formData.append("itemId", itemId);

      $.ajax({
        type: "POST",
        url: '{% url "review" %}',
        data: formData,
        processData: false,
        contentType: false,
        success: function (data) {
          if (data.is_valid) {
            setTimeout(function () {
              location.reload();
            }, 1000);
          } else {
            alert("oops....");
          }
        },
        error: function () {
          alert("Task not Done");
        },
      });
    });
  });
</script>
{%endblock%}